"""Constant paths to files and directories in the user repository."""


FILE_ISSUE_TEMPLATE_CHOOSER_CONFIG = ".github/ISSUE_TEMPLATE/config.yml"
FILE_PYTHON_PYPROJECT = "pyproject.toml"
FILE_PYTHON_REQUIREMENTS = "requirements.txt"
FILE_PYTHON_MANIFEST = "MANIFEST.in"
FILE_GITIGNORE = ".gitignore"
FILE_GITATTRIBUTES = ".gitattributes"
FILE_CC_PATH_DEF = ".github/.cc_path.txt"
DIR_GITHUB = ".github/"
DIR_GITHUB_WORKFLOWS = ".github/workflows/"
DIR_GITHUB_WORKFLOW_REQUIREMENTS = ".github/workflow_requirements/"
DIR_GITHUB_ISSUE_TEMPLATE = ".github/ISSUE_TEMPLATE/"
DIR_GITHUB_PULL_REQUEST_TEMPLATE = ".github/PULL_REQUEST_TEMPLATE/"
DIR_GITHUB_DISCUSSION_TEMPLATE = ".github/DISCUSSION_TEMPLATE/"
DIR_DEFAULT_CC = ".control"
