$schema: https://json-schema.org/draft/2020-12/schema
title: Definition of a package dependency.
type: object
additionalProperties: false
allOf:
  - $ref: module_dependency
  - oneOf:
      - required: [ conda ]
      - required: [ pip ]
    properties:
      pip:
        type: object
        required: [ spec ]
        properties:
          spec:
            title: |
              Dependency specification for pip, according to 
              [PEP 508](https://peps.python.org/pep-0508/#specification).
            description: |
              For more details, see
              [Version Specifiers](https://packaging.python.org/en/latest/specifications/version-specifiers/#id5)
              in PyPA's Python Packaging User Guide and
              [Requirement Specifiers](https://pip.pypa.io/en/stable/reference/requirement-specifiers/)
              in pip documentation.
            examples:
              - "numpy >= 1.21.2"
            type: string
      conda:
        title: Conda Specification
        type: object
        required: [ spec, channel ]
        properties:
          spec:
            title: |
              Dependency specification for Conda, according to
              [Conda Build](https://conda.io/projects/conda-build/en/stable/resources/package-spec.html#package-match-specifications).
            examples:
              - ">=1.21.2"
            type: string
          channel:
            type: string
            default: conda-forge
            examples:
              - anaconda
              - my-channel
examples:
  - - pip_spec: "numpy >= 1.21.2"
      usage: Numerical computing.
      url_source: ""
      url_homepage: ""
      url_docs: ""
      conda_spec: ""
      conda_channel: ""