$schema: https://json-schema.org/draft/2020-12/schema
title: Local Configurations
description: |
  Configurations for the project's control center.
  
  :::{admonition} Local Override
  :class: tip dropdown
  
  When working with a local clone of the repository on your computer,
  you can override these configurations 
  by creating another `config.yaml` file with the same syntax
  in the root of the repository's local directory.
  Since the files under the local directory 
  are automatically added to the `.gitignore` file,
  this file will not be tracked by Git, 
  and thus will not be pushed to the remote repository.
  This allows you to easily maintain your own local configurations 
  without affecting the remote repository.
  :::

examples:
  - cache:
      retention_days:
        api: 1
        extensions: 1

type: object
additionalProperties: false
properties:
  cache:
    title: Cache Configurations
    description: |
      Settings for various cached data.
    type: object
    additionalProperties: false
    properties:
      retention_days:
        title: Retention Time
        description: |
          Number of days to keep various cached data.
        type: object
        additionalProperties: false
        properties:
          api:
            title: API Data
            description: |
              Number of days to keep the cached data retrieved from various web APIs,
              such as GitHub repo/users data, software versions, publications etc.
            type: integer
            minimum: 0
          extensions:
            title: Extension Files
            description: |
              Number of days to keep the cached extension files (defined in `extensions.yaml`)
              retrieved from other GitHub repositories.
            type: integer
            minimum: 0
